config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  get 'home/index'

  resources :degrees
  resources :college_levels
  resources :tags
  resources :types
  resources :subjects

  get "home/admin", :path => "admin"
  post "home/admin"

  get "home/start", :path => "start"
  post "home/start"

  get "home/info", :path => "info"
  post "home/info"

  get "home/contact", :path => "contact"
  post "home/contact"

  root 'home#index'

  devise_scope :admin do
      match '/sessions/admin', to: 'devise/sessions#create', via: :post
    end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_degrees

  def index
    @home_index = true
  end

  private
    def set_degrees
      @degrees = Degree.all
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar_index.html.erb
<div class="navbar-fixed">
<nav>
    <div class="nav-wrapper">
      <a href="#" data-activates="mobile-demo" class="button-collapse"><img class="menu-ham" src="/13_krzysztofik/infoepi/assets/menu.png"></a>
      <ul class="left hide-on-med-and-down">
        <li><%= link_to 'Start', home_start_path %>
        </li>
        <li><%= link_to 'Kontakt', home_contact_path %></li>
        <li><%= link_to 'Informacje', home_info_path %></li>
      </ul>


      <% if admin_signed_in? %>
      <ul class="right hide-on-med-and-down">
        <li>
          <%= link_to 'Dodaj przedmiot', new_subject_path %>
        </li>
        <li>
          <%= link_to 'Wyloguj się', destroy_admin_session_path %>
        </li>
      </ul>
      <% end %>


      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to 'Start', home_start_path %></li>
        <li><%= link_to 'Kontakt', home_contact_path %></li>
        <li><%= link_to 'Informacje', home_info_path %></li>
        <% if admin_signed_in? %>
          <li>
            <%= link_to 'Dodaj przedmiot', new_subject_path %>
          </li>
          <li>
            <%= link_to 'Wyloguj się', new_subject_path %>
          </li>

        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/home/admin.html.erb
<% if admin_signed_in? %>

<% end %>

app/views/home/contact.html.erb
<div class="col s12 valign-wrapper content">

  <div class="col l6 offset-l6 s12 valign">
    <h1>
      Elektroniczne Przetwarzanie Informacji
    </h1>
  </div>
</div>

<div class="col s12 nammeDiv">
  <div class="col s10 offset-s1 center-align">
    <h2 id="namme">
      Autorka serwisu
    </h2>
  </div>
</div>

<div class="col s8 offset-s2 description">
  <p>

    <p style="text-align: left;">Nazywam się Iza i jestem studentką III roku na kierunku Elektroniczne Przetwarzanie Informacji.&nbsp;</p>
    <p style="text-align: left;">Jeżeli masz pytania związane z przedmiotami na tym kierunku, prowadzącymi zajęcia czy po prostu chcesz ze mną porozmawiać to pisz śmiało!<br><br> Z chęcią odpowiem na Twoje pytania.&nbsp;</p><br>
    <h2 style="text-align: center;"><strong>izabela.krzysztofik@wp.pl</strong></h2>
  </p>
</div>

<script>
$( document ).ready(function() {
  setTimeout(function(){
    $('html, body').animate({
        scrollTop: $("#namme").offset().top-100
    }, 2000);
  }, 1000);
});
</script>

app/views/home/index.html.erb
    <div class="col s12 valign-wrapper content">
      <div class="col l7 offset-l5 s12 valign">
        <% @degrees.each do |degree| %>
          <%= link_to degree.degree_name, degree, :class => "waves-effect waves-light grey btn-large position-button" %>
        <% end %>
        <a class="waves-effect waves-light grey btn-large modal-trigger enter" href="#modal1">
          <%= image_tag "enter.png", :class => "enterArrow" %>
          enter
        </a>
      </div>
    </div>


    <div class="col s12 nammeDiv">
      <div class="col s10 offset-s1 center-align">
        <h2 id="namme">
          Aplikacja dla kandydatów na studia Elektroniczne Przetwarzanie Informacji
        </h2>
      </div>
    </div>

    <div class="col s8 offset-s2 description">
      <p>

        <p>Autorem niniejszego serwisu jest Izabela Krzysztofik. Serwis ten stanowi integralną część pracy licencjackiej (kierunek: Elektroniczne Przetwarzanie Informacji), przygotowanej pod kierunkiem dr. hab. Grzegorza Bilińskiego, prof. ASP, na Wydziale Zarządzania i Komunikacji Społecznej Uniwersytetu Jagiellońskiego.</p>
<p>&nbsp;</p>
<h5 style="text-align: center;"><strong>Znajdziesz tutaj informacje o przedmiotach, o możliwościach, jakie otwierają się przed absolwentami EPI oraz o umiejętnościach jakie możesz nabyć studiując z nami!&nbsp;</strong></h3>
<p>Serwis internetowy został stworzony dla kandydat&oacute;w na studia na kierunku Elektroniczne Przetwarzanie Informacji, a także dla wszystkich, kt&oacute;rzy chcą zapoznać się z tematyką tego kierunku.&nbsp;</p>
<p>Powstał po to, aby zaprezentować Wam, co to jest "EPI" i czego możesz się nauczyć będąc studentem tego kierunku.&nbsp;</p><br><br>

  <p style="text-align: center;">Jeżeli chcesz rozpocząć swoje poszukiwania, aby dowiedzieć się co czeka każdego studenta EPI</p>
  <p style="text-align: center;">Przejdź do zakładki "Start" i poznaj nasze najskrytsze&nbsp;tajemnice!&nbsp;</p>

      </p>
    </div>


    <!-- Modal Structure -->
    <div id="modal1" class="modal">
      <div class="modal-content">
        <h4>Jak rozpocząć?</h4><br><br>
        <h6>
          Aby znaleźć przedmiot musisz najpierw wybrać, którego stopnia studia Cię interesują.<br><br> Masz do wyboru I Stopień
          , czyli studia licencjackie oraz II Stopień, czyli magisterium. <br><br>Aby uzyskać pomoc w dalszych etapach,
          naciśnij przycisk "Enter".<br><br><br>
          Powodzenia!
        </h6>
      </div>
      <div class="modal-footer">
        <a href="#!" class=" modal-action modal-close waves-effect waves-green btn">
          Rozpocznij
        </a>
      </div>
    </div>


    <script>
      $(document).ready(function(){
      $('.modal-trigger').leanModal();
      $('.backspace').remove();
      });

      $( document ).ready(function() {
        setTimeout(function(){
          $('html, body').animate({
              scrollTop: $("#namme").offset().top-80
          }, 2000);
        }, 1000);
      });

    </script>

app/views/home/info.html.erb
<div class="col s12 valign-wrapper content">

  <div class="col l6 offset-l6 s12 valign">
    <h1>
      Elektroniczne Przetwarzanie Informacji
    </h1>
  </div>
</div>

<div class="col s12 nammeDiv">
  <div class="col s10 offset-s1 center-align">
    <h2 id="namme">
      Źródła informacji
    </h2>
  </div>
</div>

<div class="col s8 offset-s2 description">
  <p>

    <h4 style="text-align: center;">Chcesz dowiedzieć się więcej?&nbsp;</h4><br>
    <ul style="list-style-type: circle;">
    <li style="text-align: center;"><a href="http://www.epi.uj.edu.pl/">Strona internetowa Elektronicznego Przetwarzania Informacji</a></li>
    <li style="text-align: center;"><a href="http://www.klk.uj.edu.pl/">Strona internetowa Katedry Lingwistyki Komputerowej</a></li>
    <li style="text-align: center;"><a href="https://www.usosweb.uj.edu.pl/">Uniwersytecki Systemu Obsługi Studiów Uniwersytetu Jagiellońskiego</a></li>
    </ul>

  </p>
</div>

<script>
$( document ).ready(function() {
  setTimeout(function(){
    $('html, body').animate({
        scrollTop: $("#namme").offset().top-100
    }, 2000);
  }, 1000);
});
</script>

app/views/home/start.html.erb
<div class="col s12 valign-wrapper content">

  <div class="col l6 offset-l6 s12 valign">
    <h1>
      Elektroniczne Przetwarzanie Informacji
    </h1>
  </div>
  <%= link_to home_index_path, class: "waves-effect waves-light grey btn-large enter" do %>
    <%= image_tag "enter.png", :class => "enterArrow" %>
    rozpocznij
  <% end %>
</div>

<div class="col s12 nammeDiv">
  <div class="col s10 offset-s1 center-align">
    <h2 id="namme">
        Jak korzystać z serwisu?
    </h2>
  </div>
</div>

<div class="col s8 offset-s2 description">

  <h2 style="text-align: center;"><strong> Witam Cię na mojej stronie!</strong></h2>
  <p><br /> Chciałabym przedstawić Ci podstawowe informacje dotyczące korzystania z niniejszego serwisu internetowego.</p>
  <p>Jeżeli trafiłeś na tą stronę, to znaczy, że jesteś zainteresowany studiami na kierunku Elektroniczne Przetwarzanie Informacji lub jesteś studentem tego kierunku i chcesz dowiedzieć się czegoś więcej na temat przedmiot&oacute;w.&nbsp;</p>
  <p>Tutaj dowiesz się <strong>jak korzystać z serwisu</strong>.</p>
  <p>Jeżeli chciałbyś dowiedzieć się dla kogo jest stworzony serwis oraz z jakimi informacjami możesz się zapoznać podczas korzystania z aplikacji, wr&oacute;ć na stronę gł&oacute;wną. Tam znajdują się pozostałe informacje.</p><br>

  <h4 style="text-align: center;"><strong>Jak znaleźć informacje o przedmiocie?&nbsp;</strong></h4><br>

  <p>Na stronie gł&oacute;wnej znajduje się Panel Wyboru Przedmiotu. Mechanizm Wyboru Przedmiotu został podzielony jest na trzy etapy.</p><br><br>

  <br><h4 style="text-align: center;">Krok I</h4><br>
  <p>Wybierz interesujący Cię&nbsp;&ldquo;I stopień&rdquo; lub &ldquo;II stopień&rdquo;</p>
  <p>Możesz także skorzystać z przycisku &ldquo;Enter&rdquo;, aby otrzymać wskaz&oacute;wkę</p>


  <br><h4 style="text-align: center;">Krok II</h4><br>
  <p>Jak wybierzesz&nbsp;interesujący Cię poziom studi&oacute;w, zostaniesz przekierowany do następnej podstrony z panelem.</p>
  <p><span style="font-weight: 400;">Tym razem zostaną wyświetlone przyciski z numerami rocznik&oacute;w. </span></p>
  <p><span style="font-weight: 400;">Do przycisku &ldquo;Enter&rdquo; dochodzi na tej podstronie także przycisk &ldquo;Powr&oacute;t&rdquo;, pozwalający na przejście do poprzedniej strony, aby zmienić swoje preferencje.</span></p>
  <p><span style="font-weight: 400;"> Po wybraniu odpowiedniego przycisku z numerem rocznika, zostaniesz przekierowany do Listy Przedmiot&oacute;w.</span></p>

  <br><h4 style="text-align: center;">Krok III</h4><br>
  <p>Twoim ostatnim zadaniem jest wyb&oacute;r jednego z wyświetlonych przedmiot&oacute;w.</p>
  <p><span style="font-weight: 400;">Po tym zostaniesz przekierowany&nbsp;do strony, w kt&oacute;rej znajduje się charakterystyka wybranego przedmiotu wraz z najważniejszymi informacjami. </span></p><br><br>

  <p style="text-align: center;"><strong>Powodzenia!&nbsp;</strong></p><br>
  <p style="text-align: center;">Pamiętaj, że na każdej podstronie znajduje się przycisk <strong>"Enter"</strong>, kt&oacute;ry wskaże Ci właściwą drogę do celu!&nbsp;</p>



</div>

<script>

$( document ).ready(function() {
  $('.backspace').remove();
  setTimeout(function(){
    $('html, body').animate({
        scrollTop: $("#namme").offset().top-100
    }, 2000);
  }, 1000);
});
</script>