config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  get 'home/index'

  resources :degrees
  resources :college_levels
  resources :tags
  resources :types
  resources :subjects

  get "home/admin", :path => "admin"
  post "home/admin"

  get "home/start", :path => "start"
  post "home/start"

  get "home/info", :path => "info"
  post "home/info"

  get "home/contact", :path => "contact"
  post "home/contact"

  root 'home#index'

  devise_scope :admin do
      match '/sessions/admin', to: 'devise/sessions#create', via: :post
    end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/degree.rb
class Degree < ActiveRecord::Base
  has_many :college_levels
end

app/controllers/degrees_controller.rb
class DegreesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]  
  before_action :set_degree, only: [:show, :edit, :update, :destroy]


  # GET /degrees
  # GET /degrees.json
  def index
    @degrees = Degree.all
  end

  # GET /degrees/1
  # GET /degrees/1.json
  def show
  end

  # GET /degrees/new
  def new
    @degree = Degree.new
  end

  # GET /degrees/1/edit
  def edit
  end

  # POST /degrees
  # POST /degrees.json
  def create
    @degree = Degree.new(degree_params)

    respond_to do |format|
      if @degree.save
        format.html { redirect_to @degree, notice: 'Degree was successfully created.' }
        format.json { render :show, status: :created, location: @degree }
      else
        format.html { render :new }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degrees/1
  # PATCH/PUT /degrees/1.json
  def update
    respond_to do |format|
      if @degree.update(degree_params)
        format.html { redirect_to @degree, notice: 'Degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @degree }
      else
        format.html { render :edit }
        format.json { render json: @degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degrees/1
  # DELETE /degrees/1.json
  def destroy
    @degree.destroy
    respond_to do |format|
      format.html { redirect_to degrees_url, notice: 'Degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degree
      @degree = Degree.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def degree_params
      params.require(:degree).permit(:id, :degree_name)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/views/degrees/_form.html.erb
<%= form_for(@degree) do |f| %>
  <% if @degree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@degree.errors.count, "error") %> prohibited this degree from being saved:</h2>

      <ul>
      <% @degree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degree_name %><br>
    <%= f.text_field :degree_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degrees/edit.html.erb
<h1>Editing Degree</h1>

<%= render 'form' %>


<%= link_to 'Back', degrees_path %>

app/views/degrees/index.html.erb
<h1>Listing Degrees</h1>

<table>
  <thead>
    <tr>
      <th>Degree</th>
      <th>Degree name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degrees.each do |degree| %>
      <tr>
        <td><%= degree.degree_name %></td>
        <td><%= link_to 'Show', degree %></td>
        <td><%= link_to 'Edit', edit_degree_path(degree) %></td>
        <td><%= link_to 'Destroy', degree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/degrees/new.html.erb
<h1>New Degree</h1>

<%= render 'form' %>

<%= link_to 'Back', degrees_path %>

app/views/degrees/show.html.erb
<div class="col s12 content valign-wrapper">

  <div class="col l7 offset-l5 s12 valign">
    <h1>
      <%= @degree.degree_name %>
    </h1>

    <% @degree.college_levels.each do |level| %>
    <%= link_to level.college_level_name, subjects_path(college_level_id: level.id), :class => "waves-effect waves-light grey btn-large position-button"%>
    <% end %>
  </div>
</div>
<a class="waves-effect waves-light grey btn-large modal-trigger enter" href="#modal1">
  <%= image_tag "enter.png", :class => "enterArrow" %>
  pomoc
</a>

<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>Jak rozpocząć?</h4><br><br>
    <h6>Aby znaleźć przedmiot musisz najpierw wybrać rok.<br><br> Masz do wyboru I, II lub III rok. <br>
Aby uzyskać pomoc w dalszych etapach,
naciśnij przycisk "Enter".<br><br><br>
Powodzenia!</h6>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-large">Rozpocznij</a>
  </div>
</div>

<script>
$(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>